name: main

on:
  push:
    branches: [ tii_build_scripts_galactic ]

jobs:
  tii-deb-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros2_distro: [ galactic ]
    steps:

      - name: Checkout rosidl_typesupport_fastrtps
        uses: actions/checkout@v2
        with:
          path: rosidl_typesupport_fastrtps
          ref: tii_build_scripts_galactic

      # Run docker build
      - name: Run fastrtps_cmake_module docker build
        env:
          ROS: 1
          ROS_DISTRO: ${{ matrix.ros2_distro }}
          PACKAGE_NAME: fastrtps_cmake_module
        run: |
          set -eux
          mkdir bin
          pushd rosidl_typesupport_fastrtps/fastrtps_cmake_module
          ./build.sh ../../bin/
          popd

      - name: Run rosidl_typesupport_fastrtps_c docker build
        env:
          ROS: 1
          ROS_DISTRO: ${{ matrix.ros2_distro }}
          PACKAGE_NAME: rosidl_typesupport_fastrtps_c
        run: |
          set -eux
          pushd rosidl_typesupport_fastrtps/rosidl_typesupport_fastrtps_c
          ./build.sh ../../bin/
          popd

      - name: Run rosidl_typesupport_fastrtps_cpp docker build
        env:
          ROS: 1
          ROS_DISTRO: ${{ matrix.ros2_distro }}
          PACKAGE_NAME: rosidl_typesupport_fastrtps_cpp
        run: |
          set -eux
          pushd rosidl_typesupport_fastrtps/rosidl_typesupport_fastrtps_cpp
          ./build.sh ../../bin/
          popd

      - uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_ARTIFACTORY_1: ${{ secrets.ARTIFACTORY_TOKEN }}

      - name: Upload to Artifactory fastrtps-cmake-module
        env:
          ARTIFACTORY_REPO: debian-public-local
          DISTRIBUTION: focal
          COMPONENT: fog-sw-sros
          ARCHITECTURE: amd64
          BUILD_NAME: fastrtps-cmake-module
          CI: true
        if: github.event_name == 'push'
        run: |
          set -exu
          jfrog rt ping
          pkg=$(find bin -name 'ros-${{ matrix.ros2_distro }}-fastrtps-cmake-module*.deb')
          pkg_name=$(basename $pkg)
          jfrog rt u --deb "$DISTRIBUTION/$COMPONENT/$ARCHITECTURE" \
                     --target-props COMMIT="$GITHUB_SHA" \
                     --build-name "$BUILD_NAME" \
                     --build-number "$GITHUB_SHA" \
                     "$pkg" \
                     "$ARTIFACTORY_REPO/$pkg_name"
          jfrog rt build-publish "$BUILD_NAME" "$GITHUB_SHA"
          jfrog rt bpr "$BUILD_NAME" "$GITHUB_SHA" "$ARTIFACTORY_REPO" \
                       --status dev \
                       --comment "development build"

      - name: Upload to Artifactory rosidl-typesupport-fastrtps-c
        env:
          ARTIFACTORY_REPO: debian-public-local
          DISTRIBUTION: focal
          COMPONENT: fog-sw-sros
          ARCHITECTURE: amd64
          BUILD_NAME: rosidl-typesupport-fastrtps-c
          CI: true
        if: github.event_name == 'push'
        run: |
          set -exu
          jfrog rt ping
          pkg=$(find bin -name 'ros-${{ matrix.ros2_distro }}-rosidl-typesupport-fastrtps-c_*.deb')
          pkg_name=$(basename $pkg)
          jfrog rt u --deb "$DISTRIBUTION/$COMPONENT/$ARCHITECTURE" \
                     --target-props COMMIT="$GITHUB_SHA" \
                     --build-name "$BUILD_NAME" \
                     --build-number "$GITHUB_SHA" \
                     "$pkg" \
                     "$ARTIFACTORY_REPO/$pkg_name"
          jfrog rt build-publish "$BUILD_NAME" "$GITHUB_SHA"
          jfrog rt bpr "$BUILD_NAME" "$GITHUB_SHA" "$ARTIFACTORY_REPO" \
                       --status dev \
                       --comment "development build"

      - name: Upload to Artifactory rosidl-typesupport-fastrtps-cpp
        env:
          ARTIFACTORY_REPO: debian-public-local
          DISTRIBUTION: focal
          COMPONENT: fog-sw-sros
          ARCHITECTURE: amd64
          BUILD_NAME: rosidl-typesupport-fastrtps-cpp
          CI: true
        if: github.event_name == 'push'
        run: |
          set -exu
          jfrog rt ping
          pkg=$(find bin -name 'ros-${{ matrix.ros2_distro }}-rosidl-typesupport-fastrtps-cpp_*.deb')
          pkg_name=$(basename $pkg)
          jfrog rt u --deb "$DISTRIBUTION/$COMPONENT/$ARCHITECTURE" \
                     --target-props COMMIT="$GITHUB_SHA" \
                     --build-name "$BUILD_NAME" \
                     --build-number "$GITHUB_SHA" \
                     "$pkg" \
                     "$ARTIFACTORY_REPO/$pkg_name"
          jfrog rt build-publish "$BUILD_NAME" "$GITHUB_SHA"
          jfrog rt bpr "$BUILD_NAME" "$GITHUB_SHA" "$ARTIFACTORY_REPO" \
                       --status dev \
                       --comment "development build"
